### ISSUE TITLE
Tutorial earlier step clientData not defined

### ISSUE THREAD

**Issue by FeynmanDNA** [ScaleDrone/react-chat-tutorial#3]
Excellent tutorial!

Just a minor issue, in your Jan 2020 version of the online tutorial (https://www.scaledrone.com/blog/tutorial-build-a-reactjs-chat-app/), at the Messages.js initial step, the instruction was to:
![image](https://user-images.githubusercontent.com/26617036/72407287-02d18c00-379a-11ea-825c-889838553c14.png)

But `member.clientData` is not available at that stage.

**Comment by ekofi** [comment]
@FeynmanDNA Same error. Any solve?

**Comment by FeynmanDNA** [comment]
@ekofi hi, the tutorial code is correct, just that the `member.clientData` is for a later section in the tutorial.

**Comment by rohansingh9001** [comment]
### You can correct that error by removing the clientData property.

#### Here's what you want to do, in the code above.
- Write `member.username` instead of `member.clientData.username`.
- Similarly, you may want to do this above as well.
- Instead of `member.clientData.color` write `member.color`.

#### Hopefully, this should resolve your issue.
